/**
 * The account-infrastructure data model.
 *
 * These run against the real database, because what is being tested is what
 * the DATABASE guarantees: that an account cannot exist without a number, an
 * organisation and a lifecycle, that the audit log cannot be rewritten, and
 * that a published product version cannot be edited under an account that is
 * trading it. None of that is provable against a mock.
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { asc, eq, sql } from 'drizzle-orm';
import { createDb, type Database } from './client.js';
import {
  accountLifecycles,
  accountProfileVersions,
  accountProfiles,
  accounts,
  auditLog,
  organizations,
  ruleTemplates,
  users,
} from './schema.js';
import { hashPassword } from '../auth/password.js';
import { recordAudit } from '../platform/audit.js';

/**
 * The reason a query failed, as Postgres stated it.
 *
 * Drizzle wraps a failure in its own "Failed query" error, so the database's
 * own message - which is the thing under test - is on the cause.
 */
async function rejection(run: () => Promise<unknown>): Promise<string> {
  try {
    await run();
  } catch (err) {
    const cause = (err as { cause?: { message?: string } }).cause;
    return `${(err as Error).message} ${cause?.message ?? ''}`;
  }
  throw new Error('expected the query to be rejected, but it succeeded');
}

let db: Database;
let close: () => Promise<void>;
let orgId: string;
let userId: string;
const created: string[] = [];

beforeAll(async () => {
  // The same database the engine suites use, not the development one: a test
  // that writes to the audit log can never take its rows back out again.
  const handle = createDb(
    process.env['TEST_DATABASE_URL'] ?? 'postgres://atlas:atlas@localhost:5432/atlas_test',
  );
  db = handle.db;
  close = async () => {
    await handle.sql.end({ timeout: 5 });
  };
  const [org] = await db.select().from(organizations).where(eq(organizations.slug, 'atlas'));
  orgId = org!.id;
  const [user] = await db
    .insert(users)
    .values({
      email: `schema-${crypto.randomUUID()}@atlas.test`,
      passwordHash: await hashPassword('x'.repeat(12)),
      displayName: 'Schema Test',
      organizationId: orgId,
    })
    .returning();
  userId = user!.id;
});

afterAll(async () => {
  for (const id of created) await db.delete(accounts).where(eq(accounts.id, id));
  await db.delete(users).where(eq(users.id, userId));
  await close();
});

describe('the organisation backfill', () => {
  it('created the organisation everything else hangs off', async () => {
    const [org] = await db.select().from(organizations).where(eq(organizations.slug, 'atlas'));
    expect(org).toBeDefined();
    expect(org!.status).toBe('ACTIVE');
  });

  /*
   * Scoped to accounts provisioned from a SYSTEM product.
   *
   * The engine suites insert accounts directly against ad-hoc templates -
   * they are fixtures for the matcher, not accounts anyone owns - so "every
   * row in the table" would be asserting something that was never true. What
   * the backfill promised is that every real account came through it.
   */
  // Vacuous on a bare test database, which is never seeded with products; it
  // is the development and production databases this is a statement about.
  it('gave every seeded account an organisation, a lifecycle and a pinned version', async () => {
    const rows = await db
      .select({
        id: accounts.id,
        organizationId: accounts.organizationId,
        lifecycleId: accounts.currentLifecycleId,
        versionId: accounts.profileVersionId,
      })
      .from(accounts)
      .innerJoin(ruleTemplates, eq(accounts.ruleTemplateId, ruleTemplates.id))
      .where(eq(ruleTemplates.isSystem, true));

    for (const row of rows) {
      expect(row.organizationId, row.id).not.toBeNull();
      expect(row.lifecycleId, row.id).not.toBeNull();
      expect(row.versionId, row.id).not.toBeNull();
    }
  });
});

describe('account numbers', () => {
  it('are generated by the database, unique, and shaped for a human to read', async () => {
    const [first] = await db
      .insert(accounts)
      .values(baseAccount(orgId, userId, 'Number test A'))
      .returning();
    const [second] = await db
      .insert(accounts)
      .values(baseAccount(orgId, userId, 'Number test B'))
      .returning();
    created.push(first!.id, second!.id);

    expect(first!.publicId).toMatch(/^SIM-\d{6}$/);
    expect(second!.publicId).not.toBe(first!.publicId);
  });

  it('are on every account that already existed', async () => {
    const rows = await db.select({ publicId: accounts.publicId }).from(accounts);
    expect(rows.length).toBeGreaterThan(0);
    for (const row of rows) expect(row.publicId).toMatch(/^SIM-\d{6}$/);
  });
});

describe('lifecycles', () => {
  it('start at one and carry the balance the account opened with', async () => {
    const [row] = await db
      .select({
        seq: accountLifecycles.seq,
        start: accountLifecycles.startingBalanceMicros,
        startedAt: accountLifecycles.startedAt,
        endedAt: accountLifecycles.endedAt,
      })
      .from(accountLifecycles)
      .limit(1);
    expect(row).toBeDefined();
    expect(row!.seq).toBeGreaterThanOrEqual(1);
    expect(row!.start).toBeGreaterThan(0);
    // The first life of an account is still running.
    expect(row!.endedAt).toBeNull();
  });
});

describe('the audit log', () => {
  it('cannot be updated', async () => {
    // Written through the ordinary recorder, so this test leaves the chain
    // intact - a hand-written row would break it for every later verification,
    // and nothing can take it back out again.
    const row = await recordAudit(db, {
      organizationId: orgId,
      actor: { type: 'SYSTEM', label: 'schema-test' },
      subjectType: 'ORGANIZATION',
      subjectId: orgId,
      action: 'test.immutability',
    });
    const message = await rejection(() =>
      db.update(auditLog).set({ action: 'tampered' }).where(eq(auditLog.id, row.id)),
    );
    expect(message).toMatch(/append-only/);
  });

  it('cannot be deleted', async () => {
    const row = await recordAudit(db, {
      organizationId: orgId,
      actor: { type: 'SYSTEM', label: 'schema-test' },
      subjectType: 'ORGANIZATION',
      subjectId: orgId,
      action: 'test.immutability',
    });
    const message = await rejection(() => db.delete(auditLog).where(eq(auditLog.id, row.id)));
    expect(message).toMatch(/append-only/);
  });
});

describe('product versions', () => {
  it('cannot be edited once published', async () => {
    const [version] = await db.select().from(accountProfileVersions).limit(1);
    expect(version).toBeDefined();
    const message = await rejection(() =>
      db
        .update(accountProfileVersions)
        .set({ notes: 'rewritten' })
        .where(eq(accountProfileVersions.id, version!.id)),
    );
    expect(message).toMatch(/append-only/);
  });

  it('carry exactly the terms of the template they were imported from', async () => {
    const templates = await db.select().from(ruleTemplates);
    expect(templates.length).toBeGreaterThan(0);
    let compared = 0;

    for (const template of templates) {
      const key = template.name
        .replace(/^Atlas /, '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-');
      const [profile] = await db
        .select()
        .from(accountProfiles)
        .where(eq(accountProfiles.key, key));
      // A template created after the import has no product, and should not.
      if (!profile) continue;
      compared += 1;

      // Pin to the ORIGINAL imported version (the lowest version number). The
      // profile may since carry later authoritative versions (a reconcile, or
      // another suite's publish onto the shared org); "imported from the template"
      // means v1, so order ascending and take the first rather than an arbitrary
      // row — this asserts exactly the import invariant and is insensitive to
      // later versions accumulating on a shared test organisation.
      const [version] = await db
        .select()
        .from(accountProfileVersions)
        .where(eq(accountProfileVersions.profileId, profile!.id))
        .orderBy(asc(accountProfileVersions.version))
        .limit(1);
      const rules = (version!.config as { rules: Record<string, unknown> }).rules;

      expect(rules['accountSizeMicros'], template.name).toBe(template.accountSizeMicros);
      expect(rules['profitTargetMicros'], template.name).toBe(template.profitTargetMicros);
      expect(rules['maxLossMicros'], template.name).toBe(template.maxLossMicros);
      expect(rules['drawdownType'], template.name).toBe(template.drawdownType);
      expect(rules['dailyLossLimitMicros'], template.name).toBe(template.dailyLossLimitMicros);
      expect(rules['maxContracts'], template.name).toBe(template.maxContracts);
      expect(rules['minTradingDays'], template.name).toBe(template.minTradingDays);
      expect(rules['flattenOnBreach'], template.name).toBe(template.flattenOnBreach);
    }

    expect(compared, 'no imported product was found to compare').toBeGreaterThan(0);
  });

});

function baseAccount(organizationId: string, ownerId: string, name: string) {
  const size = 50_000_000_000;
  return {
    organizationId,
    userId: ownerId,
    name,
    accountType: 'PRACTICE',
    status: 'PENDING',
    startingBalanceMicros: size,
    balanceMicros: size,
    highWaterMarkMicros: size,
    drawdownFloorMicros: size,
    dayStartBalanceMicros: size,
    dayStartEquityMicros: size,
  };
}
